version: '3.8'
services:
  server:
      build: 
        context: .
      restart: 
        on-failure
      environment:
        SECRETKEY: $SECRETKEY
        DATABASEURL: $DATABASEURL
        JWTALGORITHM: $JWTALGORITHM
        PORT: $PORT
        TZ: Europe/Moscow
      ports:
        - $PORT:$PORT